### ISSUE TITLE
何も表示されない

### ISSUE THREAD

**Issue by ghost** [hebiiro/AviUtl-Plugin-ObjectExplorer#1]
### コメント
Issuesに書くことではないと思いますが、ご対応をお願いします
### 症状
表示されない
- 無地で何も出てこない
- セカンドエクスプローラーも無地
- エラーなどはなし
### 思い当たる節について
- 最近AviUtlを入れ直しほかのプラグインなどもすべて入れなおした
- すべてのMicrosoft Visual C++ をアンインストールしてしまった（何を入れていいかわからず...）
### 教えていただきたいこと
- どのMicrosoft Visual C++ を入れればよいか → 修正後：Visual C++ 再頒布可能パッケージ
- その他注意事項
![image](https://user-images.githubusercontent.com/104253982/220863914-c2784964-99f8-4ac8-94d4-156510e2dffb.png)

**Comment by hebiiro** [comment]
Visual C++ 本体は必要ありません。まず拡張編集とオブジェクトエクスプローラだけを入れて正常に表示されるか確認してください。

**Comment by ghost** [comment]
AviUtl と 拡張編集 と オブジェクトエクスプローラー を入れて起動すると
「 アプリケーションを正しく起動できませんでした (0xc000007b)。[OK] をクリックしてアプリケーションを閉じてください 」
と二つ出てきました
そのままOKを押してオブジェクトエクスプローラー / セカンドエクスプローラーにチェックを入れても無地で何も出てきません

**Comment by ghost** [comment]
解決しました。
原因としては[Visual C++ 再頒布可能パッケージ 2015-2022](https://aka.ms/vs/17/release/vc_redist.x86.exe)を導入していなかったことです
ご迷惑おかけしました
