### ISSUE TITLE
高DPIで表示が崩れる問題

### ISSUE THREAD

**Issue by renorari** [hebiiro/AviUtl-Plugin-ObjectExplorer#3]
![image](https://user-images.githubusercontent.com/56919233/228218856-c3b9aa96-7163-4358-b748-2f8fe0a8223b.png)
このようにボタン等の表示が崩れます。

**Comment by renorari** [comment]
![image](https://user-images.githubusercontent.com/56919233/228219115-9c926c76-7df3-46d5-a54a-3807c93dd226.png)
わかりにくいので再up

**Comment by renorari** [comment]
![image](https://user-images.githubusercontent.com/56919233/228219277-a1885f18-b78c-4769-aa5c-73e36cffe635.png)
わかりにくいので再upします。

**Comment by hebiiro** [comment]
レイアウトが崩れているようには見えないです。それで正常です。
もし「表示が崩れる」が「ボタンの大きさが自分の好みではない」という意味なら、
aviutl.exe または ObjectExplorer.exe のプロパティで「互換性」＞「高 DPI 設定の変更」＞「高 DPI スケール設定の上書き」で調整できます。

**Comment by renorari** [comment]
<img width="1512" alt="スクリーンショット_2023-03-30_21_37_18" src="https://user-images.githubusercontent.com/56919233/228838349-a5244d66-db7e-47e5-9b4a-50e5d1534ae6.png">
aviutl.exe側の設定を変更すると通常の1/3の表示サイズになるので、非常に見づらいです。
SplitWindow等の1画面表示プラグインを使用しているため、1ウインドウのDPIを変更することはできません。
AviUtl等とDPIを合わせることはできますか？

**Comment by renorari** [comment]
<img width="1512" alt="スクリーンショット_2023-03-30_21_41_47" src="https://user-images.githubusercontent.com/56919233/228839302-c1810807-a1a8-433c-9358-a4d377691960.png">
(DPIスケールを上書きした際は、AviUtl等のスケールが小さすぎます。ですが、ObjectExplorerのスケールは適切です。)

**Comment by hebiiro** [comment]
ObjectExplorer.exe のプロパティで「互換性」＞「高 DPI 設定の変更」＞「高 DPI スケール設定の上書き」内のコンボボックスで「システム (拡張)」を選択してみてください。

**Comment by renorari** [comment]
正常なスケールで表示されました。
ありがとうございました。
